platform :osx, '10.9'
#pod 'boost', '~> 1.51.0'
#pod 'Objective-LevelDB', '~> 2.0.5'
pod 'cryptopp', :path => 'LocalPods/cryptopp'
pod 'miniupnpc', :path => 'LocalPods/miniupnpc'
pod 'leveldb', :path => 'LocalPods/leveldb'
