platform :osx, '10.9'
pod 'boost', :path => 'LocalPods/boost'
pod 'cryptopp', :path => 'LocalPods/cryptopp'
pod 'miniupnpc', :path => 'LocalPods/miniupnpc'
pod 'leveldb', :path => 'LocalPods/leveldb'
pod 'gmp', :path => 'LocalPods/gmp'
pod 'secp256k1', :path => 'LocalPods/secp256k1'
pod 'ethereum', :path => 'LocalPods/ethereum'
